apiVersion: v1
kind: Pod
metadata:
  name: "ps-pod"
  namespace: v-cluster
  labels:
    app: "ps-pod"
spec:
  containers:
  - name: ps-con
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: ROLE
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: dep
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ps-svc
  namespace: v-cluster
spec:
  selector:
    app: ps-pod
  type: NodePort
  ports:
  - port: 97
    targetPort: 80
