apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
    #  namespace: v-cluster
  labels:
    app: "pv-pvc-pod"
spec:
  containers:
    - name: nginx
      image: arunakilan/web:01
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-pv-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-pv-storage
      persistentVolumeClaim:
        claimName: nginx-pvc
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pv-pvc-svc
    #  namespace: v-cluster
spec:
  selector:
    app: "pv-pvc-pod"
  type: LoadBalancer
  ports:
  - port: 94
    targetPort: 80
