apiVersion: v1
kind: Pod
metadata:
  name: multi-con-pod
  namespace: v-cluster
  labels:
    app: multi-server
    environment: production
spec:
  containers:
  - name: server-1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: server-2
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo 'Cloud Garage'; sleep 5; done"]