apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: v-cluster
  labels:
    run: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always