apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  namespace: v-cluster
  labels:
    app: web-server
    environment: production
spec:
  containers:
  - name: web-server
    image: nginx:1.14.2
    ports:
    - containerPort: 80