apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: v-cluster
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-host
  hostPath:
    path: /app/akilan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: v-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-host
  volumeName: nginx-pv-1
