apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-1
    #namespace: v-cluster
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /app/akilan
