apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-1
    #namespace: v-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: nginx-pv-1
