apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: deployment
spec:
  ports:
  - nodePort: 30500
    port: 82
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
